### ISSUE TITLE
Add support for uninitialized fields in the constructor

### ISSUE THREAD

**Issue by ErliSoares** [vitusortner/floor#512] opened 2021-03-17 15:22 UTC
## Entity

```DART
@entity
class MaquinaTipoEntry {
  MaquinaTipoEntry({int? id, this.empresaId, this.syncId, this.nome, this.ativo = true});

  int? id;
  
  int? empresaId;

  int? syncId;

  String? nome;
  
  bool ativo;
  
  int? pessoaInclusaoId;

  int? pessoaEdicaoId;

  DateTime? dataHoraInclusao;

  DateTime? dataHoraUltimaEdicao;
}
```

## DAO

```DART
@dao
abstract class MaquinaTipoDao {
  @Query('SELECT * FROM maquina_tipo WHERE id = :id')
  Future<MaquinaTipoEntry?> findMaquinaTipoById(int id);
}

```

## Generate code

```DART
  @override
  Future<MaquinaTipoEntry?> findMaquinaTipoById(int id) async {
    return _queryAdapter.query('SELECT * FROM maquina_tipo WHERE id = ?',
        arguments: [id],
        mapper: (Map<String, Object?> row) => MaquinaTipoEntry(
            id: row['id'] as int?,
            empresaId: row['empresaId'] as int?,
            syncId: row['syncId'] as int?,
            nome: row['nome'] as String?,
            ativo: (row['ativo'] as int) != 0);
  }
```

## Expected

```DART
  @override
  Future<MaquinaTipoEntry?> findMaquinaTipoById(int id) async {
    return _queryAdapter.query('SELECT * FROM maquina_tipo WHERE id = ?',
        arguments: [id],
        mapper: (Map<String, Object?> row) => MaquinaTipoEntry(
            id: row['id'] as int?,
            empresaId: row['empresaId'] as int?,
            syncId: row['syncId'] as int?,
            nome: row['nome'] as String?,
            ativo: (row['ativo'] as int) != 0)
          ..id = row['id'] as int?
          ..pessoaInclusaoId = row['pessoaInclusaoId'] as int?
          ..pessoaEdicaoId = row['pessoaEdicaoId'] as int?
          ..dataHoraInclusao = row['dataHoraInclusao'] as DateTime?
          ..dataHoraUltimaEdicao = row['dataHoraUltimaEdicao'] as DateTime?);
  }
```

**Comment by ErliSoares** [comment] 2021-03-17 15:44
This change works for me

https://github.com/ErliSoares/floor/commit/336ff091895b3ec3058e7f3b01ac89c4608a12f5

**Comment by marcosmko** [comment] 2021-03-23 22:10
duplicate of #175

**Closed** 2021-03-25 19:41 UTC
