### ISSUE TITLE
Joint Table not Mapper in Object Class

### ISSUE THREAD

**Issue by Bramiproject** [vitusortner/floor#347] opened 2020-05-29 07:58 UTC
How to Joint Table multiple object class ?

**Comment by mqus** [comment] 2020-05-29 10:15
I'm sorry, I really don't know what you want to achieve with the little information you gave. Please write more and/or give an example.

**Comment by Bramiproject** [comment] 2020-05-29 10:22
In Java / Kotlin Environment to do a Join Table using @Embedded annotation, but if in the Library floor use what annotation to map the Object Class ?

For the ex. in Java :
`@Query("SELECT * FROM Foo")
List<FooAndBar> findAllFooAndBar();

public class FooAndBar {
    @Embedded
    Foo foo;

    @Relation(parentColumn =  "Foo.bar_id", entityColumn = "Bar.id")
    List<Bar> bar;
    // If we are sure it returns only one entry
    // Bar bar;

    //Getter and setter...
}
`

**Comment by mqus** [comment] 2020-05-29 11:24
Well, that is easy to answer now :D 

Currently, `@embedded` is not supported, but afaict it will be in the next version, thanks to @hsul4n s work in #328. But his is only a part of the things you will need so you may have to create a `@DatabaseView` with your query until we fully support arbitrary types as outputs from `@Query` functions.

I can post an example here when the embedded function was added.

**Comment by Bramiproject** [comment] 2020-05-29 11:46
> DatabaseView

Well, Thank you @mqus for your information 😃
I will wait for further information 🙏🏻

**Comment by Bramiproject** [comment] 2020-06-02 12:50
Hi @mqus,

Please your advice if use @DatabaseView how to using condition on Query in @DatabaseView ?

Ex. 
`Select * From foo Where id = :id
class Foo{
   int Id;
   Foo(Id)
}
`

**Comment by mqus** [comment] 2020-06-02 15:05
Parameters won't work in the declaration of a databaseview.

**Comment by mqus** [comment] 2020-07-12 12:25
Closing as a duplicate of #9 and #94 . Please reopen if you disagree :)

**Closed** 2020-07-12 12:25 UTC
