### ISSUE TITLE
Query return type

### ISSUE THREAD

**Issue by tajaouart** [vitusortner/floor#426] opened 2020-11-04 10:36 UTC
I'm trying to return the number of rows in database but,
query method doesn't accept a String, int or Object as a return type other than my entities ??

ex:
 @ Query('SELECT COUNT(id) FROM Question')
  Future < String > getNumberOfQuestions();

Error:

NoSuchMethodError: The getter 'constructor' was called on null.
Receiver: null
Tried calling: constructor
[INFO] Running build completed, took 10.6s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 77ms

[SEVERE] Failed after 10.6s
pub finished with exit code 1

**Comment by vitusortner** [comment] 2020-11-06 17:06
As of now, returning integers is not supported but we're working on something here #361.

**Comment by LuckyJayce** [comment] 2020-12-23 12:56
I think the return value will be more general if it can support the definition of map

    @Query('SELECT COUNT(id) FROM Question')
    Future<Map<String, dynamic>> getNumberOfQuestions();

**Comment by vitusortner** [comment] 2020-12-26 10:14
This is already possible by using your database's `database` property. It gives access to the underlying SQLite (sqflite) database. https://github.com/vitusortner/floor/blob/1db7738395502ca06a0adabb8943e0750c01fd4d/floor/lib/src/database.dart#L14

**Comment by alectogeek** [comment] 2020-12-26 15:29
> This is already possible by using your database's `database` property. It gives access to the underlying SQLite (sqflite) database.

Yes, but only as a `future`. Sometimes it's useful to get `COUNT()` as `Stream`

**Comment by mqus** [comment] 2021-04-23 14:24
This is more or less the same issue as #200 so I'll close this as a duplicate of it. Please be sure to subscribe/enable notifications there to keep tabs on this feature.

**Closed by mqus** 2021-04-23 14:24 UTC
