### ISSUE TITLE
Can't primaryKey be String type?

### ISSUE THREAD

**Issue by Henvealf** [vitusortner/floor#313] opened 2020-04-15 14:23 UTC
When I create a entity like this: 
```
class User {
  @PrimaryKey()
  final String id;
}
```

After `flutter packages pub run build_runner build`, the dao mapper of generated in `*.g.dart` file is :
```
id: row['id'] as double,
```

I need to change it manually every build as:

```
id: row['id'] as String,
```
Otherwise it won't work when operate db :

```
type 'String' is not a subtype of type 'double' in type cast
```

Is this a bug？

Version：

```
dependencies:
  floor: ^0.12.0

dev_dependencies:
  floor_generator: ^0.12.0
  build_runner: ^1.7.3
```

**Comment by Henvealf** [comment] 2020-04-20 13:15
🤷‍♀️

**Comment by vitusortner** [comment] 2020-04-20 16:22
Has the problem been solved already?

**Comment by Henvealf** [comment] 2020-04-22 08:03
> Has the problem been solved already?

Not yet,  I change it manually every build as:

**Comment by Henvealf** [comment] 2020-04-22 08:05
> Has the problem been solved already?

Not yet, I solved this by manually modifying the `*.g.database` after each build.

**Comment by TheVinhLuong** [comment] 2020-04-23 14:37
@Henvealf Are you on the latest version? I have a string as a primary key too and everything works fine.

**Comment by mqus** [comment] 2020-04-23 17:03
Where did you get this version from? Afaict there is only a 0.12.0. But I'll take a look and report back.

**Comment by TheVinhLuong** [comment] 2020-04-23 17:53
@mqus my bad, it is 0.12.0.

**Comment by mqus** [comment] 2020-04-23 19:59
I just adjusted the integration tests (`id` of `Dog` to be of type `String`) and could not observe your bug. everything is generated as expected:
In `TestDatabase::open`
```dart
      onCreate: (database, version) async {
        await database.execute(
            'CREATE TABLE IF NOT EXISTS `person` (`id` INTEGER, `custom_name` TEXT NOT NULL, PRIMARY KEY (`id`))');
        await database.execute(
            'CREATE TABLE IF NOT EXISTS `dog` (`id` TEXT, `name` TEXT, `nick_name` TEXT, `owner_id` INTEGER, FOREIGN KEY (`owner_id`) REFERENCES `person` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, PRIMARY KEY (`id`))');
        await database.execute(
            'CREATE INDEX `index_person_custom_name` ON `person` (`custom_name`)');

        await callback?.onCreate?.call(database, version);
      },
```

in `_$DogDao`
```dart
  static final _dogMapper = (Map<String, dynamic> row) => Dog(
      row['id'] as String,
      row['name'] as String,
      row['nick_name'] as String,
      row['owner_id'] as int);
```
And the tests ran through successfully after also changing the calls to the constructor in the tests.

I'll assume that you already tried to remove the generated file and regenerate it from scratch, so can you share a bit more of your code, maybe a reproducable example?

**Comment by Henvealf** [comment] 2020-04-25 09:34
@mqus 

`entities.dart`:

```
import 'package:equatable/equatable.dart';
import 'package:floor/floor.dart';
import 'package:uuid/uuid.dart';

class CommonField extends Equatable{

  @ColumnInfo(name: 'create_time', nullable: false)
  final String createTime;

  @ColumnInfo(name: 'update_time')
  final String updateTime;

  @ColumnInfo(nullable: false)
  final bool avail;

  CommonField(
      this.updateTime,
      this.avail, {
        createTime,
      }) : this.createTime = createTime ?? DateTime.now().toString();

  @override
  List<Object> get props => [];
}

@Entity(tableName: 'groups')
class Group extends CommonField{

  final String name;

  @PrimaryKey()
  final String id;

  final String content;

  Group(
    this.name, {
    id,
    this.content = '',
    String createTime,
    String updateTime,
    bool avail = true
  }) : this.id = id ?? Uuid().v4(),
       super(updateTime, avail);


  @override
  String toString() {
    return 'Group{name: $name, id: $id, content: $content}';
  }

  @override
  List<Object> get props => [id, name, content];
}
```

`dao.dart`

```
@dao
abstract class GroupDao {

  static const _QUERY_ALL = 'xxxxxx';

  @Query(_QUERY_ALL)
  Future<List<Group>> findAllGroups();
}
```

`database.dart`:

```
@Database(version: 1, entities: [Group])
abstract class AppDatabase extends FloorDatabase {
  GroupDao get groupDao;
}
```

---

after `flutter packages pub run build_runner build`,  the part of `database.g.dart`:

```
class _$GroupDao extends GroupDao {
  _$GroupDao(this.database, this.changeListener)
      : _queryAdapter = QueryAdapter(database);

  final sqflite.DatabaseExecutor database;

  final StreamController<String> changeListener;

  final QueryAdapter _queryAdapter;

  static final _groupsMapper = (Map<String, dynamic> row) => Group(
      row['name'] as String,
      id: row['id'] as double,
      content: row['content'] as String,
      createTime: row['create_time'] as String,
      updateTime: row['update_time'] as String,
      avail: (row['avail'] as int) != 0);

  @override
  Future<List<Group>> findAllGroups() async {
    return _queryAdapter.queryList('xxxxxx', mapper: _groupsMapper);
  }
}
```

You can see the `double` in database.g.dart.

**Comment by mqus** [comment] 2020-04-25 15:39
Thank you very much!  I could reproduce it now.
Regarding the solution: the dart analyzer tool pointed me to your constructor (Missing parameter type for id). 
If I write 
```dart
Group(
    this.name, {
    String id,
    this.content = '',
    String createTime,
    String updateTime,
    bool avail = true
  }) : this.id = id ?? Uuid().v4(),
       super(updateTime, avail);
```
(note the additional `String ` before `id`), then everything gets generated just fine. Why it assumes that it should be `double` is something that I'll investigate now. 

Btw, the analyzer also complained about a missing parameter type of `createTime` in the constructor of `CommonField`. 
I get notified about those things by Android studio automatically, but you can also run the analyzer manually by executing
```
flutter analyze
```
I hope I could help :wink:

**Comment by mqus** [comment] 2020-04-25 15:50
Ah right, `'double'` is the fallback string, so even if the type was null for any constructor argument (not just the primary key), it would fall back to using `'double'`.
https://github.com/vitusortner/floor/blob/cfa25d3b01b69a7ce281c9043604b8657264e03c/floor_generator/lib/processor/queryable_processor.dart#L77-L93

We should probably generate an error there if the type does not get matched. But this code is currently subject to change anyway due to #318 . What do you think, @vitusortner ?

**Comment by vitusortner** [comment] 2020-05-27 19:48
Such cases won't be possible anymore with the type converters implementation because we'll be making sure that used values and types are database-compatible. If they're not database-compatible out of the box, we'll be looking for matching type converters. If no converter can be found, an error will be thrown.

**Comment by mqus** [comment] 2020-05-27 21:57
This case was a special case where no type was set for a variable, so we should definitely look out for it (or test for it). But in either case this is an easy fix, if it occurs again. 

I will be closing this issue, as @Henvealf hasn't mentioned any other issues. If you still have this problem please reopen this issue or open a new one.

**Closed by mqus** 2020-05-27 21:57 UTC
Labels: question
