### ISSUE TITLE
Complex Types with Floor and advanced query

### ISSUE THREAD

**Issue by claudneysessa** [vitusortner/floor#456] opened 2020-12-21 15:00 UTC
hello my friends, I use FLOOR I think it's a fantastic tool but I have the need to create complex types and advanced query.
With it in my case I need to make objects with up to 3 levels.

Could someone give me a light?

Example:

class Order
{
int orderId;
List <Items> items;
}

class Order Items
{
int orderId;
int itemId;
List <ItensComponents> components;
}

class ItemsComponents
{
int orderId;
int itemId;
int componentId;
}

I would like to bring everything in a single object where it would be possible to access and persist, update or even delete it through the PAI object.

I need to access the elements of the parent object as follows.

Example:
order.itens [2] .components [1] .componentId

However, it would be interesting if this was loaded together and called the parent object [Order]

If anyone has a solution link or can help me I would be very grateful!

**Comment by mqus** [comment] 2021-04-23 15:12
I think you want a combination of `@embedded` (#9) and `@Relation` (#47), both of which are not implemented yet.

But I also want to stress, that floor will probably never be able to map _operations on that object_ to the database (e.g. removing an element from the list will automatically remove it in the database). It did sound a little like you meant it that way, not sure if you meant that ;) .

So as this is mainly a duplicate of the mentioned tickets, I will close this issue. Feel free to reopen if you think this decision was wrong :)

**Closed by mqus** 2021-04-23 15:12 UTC
