### ISSUE TITLE
@ColumnInfo  Support  defaultValue

### ISSUE THREAD

**Issue by CrazyWalk** [vitusortner/floor#587] opened 2021-07-16 06:27 UTC
Android Room @ColumnInfo support defaultValue

```
@ColumnInfo(name = "name", defaultValue = "")
var name: String = ""
```

sql
```
CREATE TABLE IF NOT EXISTS `book` (`id` TEXT NOT NULL, `name` TEXT NOT NULL DEFAULT '', `seq_id` INTEGER NOT NULL DEFAULT -1, `deleted` INTEGER NOT NULL DEFAULT 0, `sync_status` INTEGER NOT NULL DEFAULT 0, `created_at` INTEGER NOT NULL DEFAULT -1, `updated_at` INTEGER NOT NULL DEFAULT -1, `book_order` INTEGER NOT NULL DEFAULT -1, PRIMARY KEY(`id`))
```

now floor is not support 'DEFAULT' . Hope to add this feature

**Comment by mqus** [comment] 2021-07-16 11:17
Duplicate of #256

**Closed by mqus** 2021-07-16 11:17 UTC
