### ISSUE TITLE
Order of parameters

### ISSUE THREAD

**Issue by Ryszardenko** [vitusortner/floor#480] opened 2021-01-08 10:46 UTC
Hi,
there is a small problem with Queries. Actually function parameters must be in the same order as are in Query. 

example:

//this doesn;t update - different order
  @Query('UPDATE DateObject SET date= :date WHERE id = :id')
  Future<void> updateDate(int id, String date);

//this works fine
  @Query('UPDATE DateObject SET date= :date WHERE id = :id')
  Future<void> updateLastSeen(String date, int id);

Possible to fix?

**Comment by vitusortner** [comment] 2021-01-10 17:33
Hi! This is a known problem and we're working on a fix in #361. Until it is merged, there is no way around sticking to the order.

**Comment by LuckyJayce** [comment] 2021-02-19 02:24
@vitusortner 

I have another problem  
One parameter needs to be used multiple times
such as：

    @Query('SELECT * FROM $table_plan where title like :searchText or detail like :searchText')
    Future<List<Plan>> searchPlans(String searchText);
error:
   SQL query arguments and method parameters have to match.
But if you use variable name matching, this can be solved at the same time

**Comment by vitusortner** [comment] 2021-02-19 08:31
Hi! This is caused by a current limitation of floor.

**Comment by vitusortner** [comment] 2021-03-16 07:31
Closing this issue as it's a duplicate of #224.

**Closed by vitusortner** 2021-03-16 07:31 UTC
