### ISSUE TITLE
transaction works incorrectly

### ISSUE THREAD

**Issue by alectogeek** [vitusortner/floor#225] opened 2019-12-09 19:53 UTC
I have a method marked with @transaction annotation where I fetch some data from the network and do multiple inserts/updates via dao.insert/update (they marked as with @insert and @update methods accordingly). But if one of the operations is aborted, changes are not rolled back. What can cause the problem?

**Comment by mqus** [comment] 2020-05-27 10:31
Do you still have this problem? If yes, could you please share some code with us to help us reproduce the issue? One idea I have right now: is the method marked with `@transaction` part of a DAO class?

**Comment by mqus** [comment] 2020-07-12 12:28
Closing due to inaction. Please reopen if you have an update :)

**Closed by mqus** 2020-07-12 12:28 UTC
Labels: bug, question
