### ISSUE TITLE
Entity with field another entity

### ISSUE THREAD

**Issue by Jparrgam** [vitusortner/floor#369] opened 2020-07-08 06:41 UTC
Hi @vitusortner, i have a question it is possible that an entity can contain other entities for example: 
`@Entity(tableName: 'configuration')
class Configuration { 
  Settings settings;
}`

`@Entity(tableName: 'configuration')
class Settings {
  //fields
}`

**Comment by mqus** [comment] 2020-07-12 12:12
There are mainly two ways of achieving what you want and both are sadly not yet available. 
1. If you want `Settings` to be its own table in the database and query it like one, then you want something like `@Relation` (Feature Request #47 )
2. If you want `Settings` to be embedded into `Configuration` and the table of `Configuration` simply including all the fields of `Settings`, then you want `@Embedded` (Feature Request #9, Implementation: #328 )

As this is mainly a duplicate of those two features, I will close this as a duplicate. If you are disagreeing, please reopen :)

**Closed by mqus** 2020-07-12 12:12 UTC
