### ISSUE TITLE
Undefined StreamController, undefined PersonMapper

### ISSUE THREAD

**Issue by grappetite-ali** [vitusortner/floor#110] opened 2019-04-03 06:30 UTC
After running command `flutter packages pub run build_runner build`, i am getting syntax error in database.g.dart file which is _undefined StreamController_ and undefined _PersonMapper_.

**pubspec.yaml**
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.2.0
  build_runner: ^1.2.8

```

**database.dart**
```
import 'package:floor/floor.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
import './person.dart';
import './person-dao.dart';

part 'database.g.dart'; // the generated code will be there

@Database(version: 1, entities: [Person])
abstract class AppDatabase extends FloorDatabase {
  static Future<AppDatabase> openDatabase() async => _$open();

  PersonDao get personDao;
}
```

**person.dart**
```
import 'package:floor/floor.dart';

@entity
class Person {
  @primaryKey
  final int id;

  final String name;

  Person(this.id, this.name);
}
```

**person-dao.dart**
```
import 'package:floor/floor.dart';
import './person.dart';

@dao
abstract class PersonDao {
  @Query('SELECT * FROM Person')
  Future<List<Person>> findAllPersons();

  @Query('SELECT * FROM Person WHERE id = :id')
  Future<Person> findPersonById(int id);

  @insert
  Future<void> insertPerson(Person person);
}
```

**Comment by vitusortner** [comment] 2019-04-03 07:10
Hi and thanks for the report! The problem is caused by the missing `dart:async` import in the file where your database is defined. I'll update the README asap.

Did this solve the error?

```diff
+ import 'dart:async';

import 'package:floor/floor.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
import './person.dart';
import './person-dao.dart';

part 'database.g.dart'; // the generated code will be there

@Database(version: 1, entities: [Person])
abstract class TestDatabase extends FloorDatabase {
  static Future<TestDatabase> openDatabase() async => _$open();

  PersonDao get personDao;
}
```

**Comment by grappetite-ali** [comment] 2019-04-03 07:15
Yeah, i looked into the source code and found two issues. 1st one is that you just mentioned, it will solve undefined StreamController issue, and 2nd is to annotate your entity class with annotation `@Entity`, instead of `@entity`. It will fix issue of undefined PersonMapper error.
Please update this in doc too.

Thanks @vitusortner

**Comment by vitusortner** [comment] 2019-04-03 07:31
`@entity` is meant to work as well. A fix will be introduced with the next release.

**Closed** 2019-04-03 08:37 UTC
