### ISSUE TITLE
can @Query support part attributs?

### ISSUE THREAD

**Issue by libinwalan** [vitusortner/floor#378] opened 2020-07-23 14:53 UTC
I want to query id from a table, so ,i add this to the dao file
` @Query('SELECT id FROM Taskitem')
 Future<List<int>> findAllTaskitemIdList();`

but this build error with output
"[SEVERE] floor_generator:floor_generator on lib/entity/database.dart:
Error running FloorGenerator
NoSuchMethodError: The getter 'name' was called on null."

So, can floor support this? how can i do ?  
thanks

**Comment by mqus** [comment] 2020-07-23 22:28
This is pretty much the same issue as #374 and is that way because primitive Values as returns from dao methods are not supported yet. They are already implemented though (#361) and just need a review and some testing. If you check out the branch and reference floor through a path reference in your pubspec then you can try it out right now. Alternatively you can look at the linked issues (e.g. #200) to find workarounds

**Comment by mqus** [comment] 2021-04-23 14:20
I'll close this as a duplicate of #200.

**Closed by mqus** 2021-04-23 14:20 UTC
